### ISSUE TITLE
seasonality: Role of stationarity

### ISSUE THREAD

**Issue by christophsax** [srlanalytics/bdfm#24]
You mentioned that:

> SeasAdj_WE() requires data is stationary. 

Perhaps we could do a stationarity test, log-diff, adjust and level back again? 

It think for a seasonal adjustment routine, the following should work out of the box:

```
seas_we(AirPassengers)
```

**Comment by christophsax** [comment]
stationarity test, log-diff, adjust and level back again:

If we do this properly, we can use it both in `seas_we` and `dfm`. 

We could include it with an option: `auto.stationary = TRUE` (or something like this). A message would tell the user what has been done.

**Comment by srlanalytics** [comment]
What I actually do in practice is use a `loess()` regression to de-trend non-stationary data (usually after taking logs). This tends to yield more accurate results (in terms of out of sample backtesting) than taking log differences of non-stationary data. Thus the function works very much like `seas()`. However, just de-trending once for stationarity reasons is fine... stationary trends will be handled by the estimated factor leaving a pretty clean estimate of seasonal effects. The best approach may be to always de-trend with `loess()` (this won't hurt anything for data that is stationary) with two inputs:
`transform = auto` 
and
'span = 0.5`
or something. If there are no negative values in the data I would set `auto` to take logs of the data; otherwise leave it in levels. We could also allow `span = NULL` to imply not de-trending with `loess()`.

**Comment by christophsax** [comment]
Sounds good, I will give this a try.

**Comment by christophsax** [comment]
I guess this does not work that well in `dfm`, e.g., in forecasts? How would you handle non-stationarity there? We also need to forecast the trend somehow.

**Comment by christophsax** [comment]
All persuading. Will give this a try a well. 

Two more questions on this:

1. If you had a monthly non-stationary series (e.g., exports), and a quarterly non-stationary series (e.g., exports) (both seas. adj.), would you log diff the first m-o-m, the second q-o-q? Perhaps annualizing the resulting log-diffs (multiplying by 12, 4, resp.) is sufficient to make it work with `cumsum`-re-leveling? How about daily data? Multiplying by 365.25? Or 365/366?

2. Generally, dfm deals with `NA` on its own, but If we have an `NA` in a non-stationary series we cannot use this feature, right? So if we have `NA` in a non-stationary series, we need to impute it before?

**Comment by srlanalytics** [comment]
On the first point:

That's a superb question. This framework does not explicitly deal with mixed frequency data... doing that properly requires aggregating factors with a helper matrix. For quarterly-monthly data in levels one would simply aggregate factors to predict quarterly series as [1/3  1/3  1/3] [x_{t}  x_{t-1}  x_{t-2}]. If the data is differenced, the aggregation gets a bit more complicated (see the intro to mixed frequency data [here](http://srlquantitative.com/docs/Factor_Models.pdf)).  However, a nice trick is that if instead of differencing monthly data MoM, we use  x_{t} - x_{t-3} we're back to the simple aggregation case above. However, since this iteration of `bdfm` does not support mixed frequency data (I've got lots of code that does but it's not very user friendly...) that model will still be misspecified. You can run it, and the results might be interesting, but... 

The way you get around it, and the way you can properly specify a mixed frequency model in this framework, it to write high frequency variables (monthly in this example) as follows:

x_m = (x_t + x_{t-1} + x_{t-2}) - (x_{t-3} + x_{t-4} + x_{t-5}) 

Then you have a correctly specified mixed frequency model that you can plug into `bdfm`. I would only use this approach if you're interested in nowcasting/predicting quarterly variables (i.e. the low frequency stuff), but it should work fairly well. If you wanted to do it really properly you could even do the above aggregation _before_ taking logs of variables... then you'd have a really slick model. Also, no need to scale things up or down due to frequency (i.e. multiply by 3 or whatever).

On the second point:

Generally no. If we have a mixed frequency model with monthly-quarterly data, we want to difference the monthly stuff as I described above. Technically, if any element of 

x_m = (x_t + x_{t-1} + x_{t-2}) - (x_{t-3} + x_{t-4} + x_{t-5}) 

is NA the whole thing should be NA. What I do in practice is to use the average of

x_t + x_{t-1} + x_{t-2}

and

x_{t-3} + x_{t-4} + x_{t-5}

If one value is missing, treat the average as data; if two are missing, call it NA. 

For the quarterly data we just difference quarter 4 and quarter 3, quarter 3 and quarter 2, and so on.  If a value is missing we  just have NA's in the differenced data. 

I'll put together a short example to try to clarify all this... will let you know when I've got it running.

**Comment by srlanalytics** [comment]
This should all be cleaned up as well... the function now automatically decides on whether to take logs (default is `'auto'`; the other options are `'log'` or 'none'`) and de-trends unless told to do otherwise (default is span = 0.5, set to span=NULL to turn off de-trending).
