### ISSUE TITLE
Heuristics: No of factors, lags

### ISSUE THREAD

**Issue by christophsax** [srlanalytics/bdfm#33]
How did you came up with `factors = 3, lags = 3` in the US GDP example:

```r
est <- dfm(Y, factors = 3, lags = 3, frequency_mix = freq, differences = differences, nu_r = nu_r,
           identification = "PC_full", store_idx = 1, reps = 1000, burn = 500, loud = TRUE)
```

You probably tried out and came out with some 'reasonable' value. Any idea how we could find a good starting point. I would assume that the number of factors has some relationship with the number of series in `Y`. E.g., if we only have 2 series, we probably want to use one factor only. If we have many series, we want to use a few more factors. 

The number of lags may be related to the frequency of the series?

**Comment by srlanalytics** [comment]
Regarding default factors, it occurred to me I had set it to 1 since (a) this gives what should be a very good leading index (i.e. good predictive power) for the data entered and (b) it works with any number of series, from 1 to lots. 

Regarding lags, yes, 3 was because there are three months in a quarter. Thus if we wanted to set the default number of lags to the max number of high frequency periods in a now frequency period (i.e. using the auto frequency detection) that would probably be a pretty reasonable thing to do.

**Comment by christophsax** [comment]
Is 1 factor also reasonable for a larger model? Would it make sense to try to be smart. E.g.,

- 1 factor, for 1 to 5 series
- 2 factors for 6 to 10 series
- 3 factors for more than 11 series

**Comment by SethOttoQuant** [comment]
I think it better to stick with 1 factor as default. This immediately gives a clear interpretation to the model and will still have strong predictive power for nowcasting, though typically less predictive power than models with more factors for forecasting. Regarding interpretation, with one factor, that factor is the index that optimizes predictive power for all of the series included in the model. It is arguably the best possible leading index of included series, where "best possible" is based on the likelihood function. With multiple factors, interpretation depends on the identification routine used. Also, a one factor model will always run faster, so that using more factors should be justified somehow.

**Comment by christophsax** [comment]
Ok, sounds good to me. Thanks.
